/** Non-model keys in config.agent — preserved when clearing all overrides. */
export const CONFIG_AGENT_NON_MODEL_KEYS = [
  "default",
  "forceBackground",
  "graceTurns",
  "showCost",
  "showTools",
  "showTurns",
  "showInput",
  "showOutput",
  "showContext",
  "showTime",
  "deltaInputTokens",
  // widget* 设置已随树状渲染移除；保留键名以免存量配置文件里的
  // 这些键被 clearAllModelOverrides 当作按类型模型覆盖处理。
  "widgetMaxLines",
  "widgetMaxLinesCompact",
  "widgetDescLengthFull",
  "widgetDescLengthCompact",
  "widgetCompact",
  "widgetShortcut",
  "systemPromptMode",
  "includeContextFiles",
  "defaultThinking",
  "defaultMaxTurns",
  "loadSkillsImplicitly",
  "loadExtensionsImplicitly",
  "disableDefaultAgents",
  "outputThinkingBufferSize",
];
